# Generated by Django 4.1.3 on 2022-12-15 10:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wishes", "0003_alter_wishlist_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="house_number",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="House number"
            ),
        ),
        migrations.AddField(
            model_name="wishlist",
            name="age",
            field=models.PositiveSmallIntegerField(default=10, verbose_name="Age"),
        ),
        migrations.AddField(
            model_name="wishlist",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created at",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                        ],
                        default="new",
                        help_text="Status of a package.",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SMALL", "Small"),
                            ("MEDIUM", "Medium"),
                            ("LARGE", "Large"),
                        ],
                        max_length=20,
                        verbose_name="Size",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "wish_list",
                    models.OneToOneField(
                        help_text="A relevant wish list the package belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package",
                        related_query_name="package",
                        to="wishes.wishlist",
                        verbose_name="A wish list",
                    ),
                ),
            ],
        ),
    ]
